# Generated by Django 5.0.14 on 2025-11-26 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0067_slackwritemessageworkflowaction"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RepeatElement",
            new_name="IterateElement",
        ),
        migrations.AlterField(
            model_name="iterateelement",
            name="horizontal_gap",
            field=models.IntegerField(
                db_default=0,
                default=0,
                help_text="The amount of horizontal space between iterated elements.",
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Value cannot be less than 0."
                    ),
                    django.core.validators.MaxValueValidator(
                        2000, message="Value cannot be greater than 2000."
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="iterateelement",
            name="items_per_row",
            field=models.JSONField(
                default=dict,
                help_text="The amount of iterations per row, per device type. "
                "Only applicable when the orientation is horizontal.",
            ),
        ),
        migrations.AlterField(
            model_name="iterateelement",
            name="vertical_gap",
            field=models.IntegerField(
                db_default=0,
                default=0,
                help_text="The amount of vertical space between iterated elements.",
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Value cannot be less than 0."
                    ),
                    django.core.validators.MaxValueValidator(
                        2000, message="Value cannot be greater than 2000."
                    ),
                ],
            ),
        ),
    ]
