# Generated by Django 5.0.13 on 2025-10-30
from django.db import migrations, models


def add_field_metadata_columns(apps, schema_editor):
    """
    Add field_metadata JSONB column to all existing tables.

    This column stores metadata for all fields in a row using a JSON structure
    where field IDs are keys. This allows any field type to store status,
    error information, timestamps, or other metadata about their values.

    Example structure:
    {
        "123": {
            "status": "success",
            "generated_at": "2024-01-15T10:30:00Z"
        },
        "456": {
            "status": "error",
            "error_message": "API rate limit exceeded"
        }
    }
    """
    connection = schema_editor.connection
    Table = apps.get_model("database", "Table")

    with connection.cursor() as cursor:
        for table in Table.objects.all():
            table_name = f"database_table_{table.id}"

            # Check if table exists
            cursor.execute(
                """
                SELECT EXISTS (
                    SELECT FROM information_schema.tables
                    WHERE table_schema = 'public'
                    AND table_name = %s
                )
                """,
                [table_name],
            )

            if not cursor.fetchone()[0]:
                continue

            # Add JSONB column with empty dict default
            # Using db_default ensures the default is at the database level
            # This makes the ALTER TABLE instant (no table rewrite)
            cursor.execute(
                f"""
                ALTER TABLE {table_name}
                ADD COLUMN IF NOT EXISTS field_metadata JSONB
                NOT NULL DEFAULT '{{}}'::jsonb
                """
            )

            # Add GIN index for efficient JSONB queries
            # This allows fast queries like:
            # WHERE field_metadata->'123'->>'status' = 'error'
            cursor.execute(
                f"""
                CREATE INDEX IF NOT EXISTS
                {table_name}_field_metadata_gin
                ON {table_name} USING GIN (field_metadata)
                """
            )

    # Mark all tables as having the column
    Table.objects.all().update(field_metadata_column_added=True)


def reverse_migration(apps, schema_editor):
    """Remove field_metadata column from all tables."""
    connection = schema_editor.connection
    Table = apps.get_model("database", "Table")

    with connection.cursor() as cursor:
        for table in Table.objects.all():
            table_name = f"database_table_{table.id}"

            cursor.execute(
                f"""
                DROP INDEX IF EXISTS {table_name}_field_metadata_gin
                """
            )

            cursor.execute(
                f"""
                ALTER TABLE {table_name}
                DROP COLUMN IF EXISTS field_metadata
                """
            )

    Table.objects.all().update(field_metadata_column_added=False)


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0200_fix_to_timestamptz_formula"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="field_metadata_column_added",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Indicates whether the table has had the field_metadata column added.",
                null=True,
            ),
        ),
        migrations.RunPython(add_field_metadata_columns, reverse_migration),
    ]
