# Generated by Django 5.0.14 on 2025-11-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0200_fix_to_timestamptz_formula"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="field_metadata_column_added",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the table has had the field_metadata column added.",
                null=True,
            ),
        ),
    ]
