# Generated by Django 5.0.14 on 2025-11-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0201_table_field_metadata_column_added"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="field_metadata_column_added",
            field=models.BooleanField(
                db_default=True,
                default=True,
                help_text="Indicates whether the table has had the field_metadata column added.",
                null=True,
            ),
        ),
    ]
